### ISSUE TITLE
Using _ instead of lodash

### ISSUE THREAD

**Issue by SenHeng** [rockabox/ng-lodash#28]
Would it be possible to change `lodash` to `_`?

Would make code shorter and easier to read.

**Comment by nwhite89** [comment]
I am open to do this however I am aware that this would cause any one currently using this module to have to move over. I suppose one possible solution would be to build a second set of the JS file using `_` rather than `lodash`. 

Before doing this I'm interested if this is something that others using the module would want also

**Comment by devsaik** [comment]
Please don't change it _ . One good reason some of us are  using this library is because of it's alias lodash.

Thanks, 
Sai




On Thu, Nov 5, 2015 at 1:53 AM -0800, "Nick White" <notifications@github.com> wrote:












I am open to do this however I am aware that this would cause any one currently using this module to have to move over. I suppose one possible solution would be to build a second set of the JS file using _ rather than lodash. 



Before doing this I'm interested if this is something that others using the module would want also

**Comment by nwhite89** [comment]
@devsaik yeah I understand that and wouldn't want to do a full switch as fully aware of the impact on this. I'm considering whether or not it's worth doing allowing either to be used basically having different files for it but not sure if it really truly is necessary.

**Comment by forcewill** [comment]
@SenHeng  why not create an alias with
      
    .constant('_',  lodash)

**Comment by thefabulousdev** [comment]
+1

**Comment by ptitgraig** [comment]
+1 for this change in the next major version (1.0.0 for example ?)
